#!/bin/sh
#
# Copyright (C) 2014 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH="/config/services/pxe"
SERVICE_XPATH_ENTRY="${SERVICE_XPATH}/entries/entry"

PXE_SHARED_FOLDER_REF=$(omv_config_get "${SERVICE_XPATH}/sharedfolderref")
PXE_PATH=$(omv_get_sharedfolder_path "${PXE_SHARED_FOLDER_REF}")
PXE_CONFIG_PATH="${PXE_PATH}/pxelinux.cfg"
PXE_CONFIG="${PXE_CONFIG_PATH}/default"
PXE_USE_NEW_SYSLINUX=$(omv_config_get "${SERVICE_XPATH}/use_new_syslinux")

command=`echo $2 | cut -d \  -f 1`
package=`echo $2 | cut -d \  -f 2`

# Nothing more to do
ENABLED=$(omv_config_get "${SERVICE_XPATH}/enable")
if [ "${ENABLED}" != "1" ] && [ "${command}" != "syslinux" ] && [ "${command}" != "syslinux_version" ]; then
	exit 0
fi

# Syslinux
syslinux_version() {
	#if [ "${PXE_USE_NEW_SYSLINUX}" != "1" ] && 
	if [ -f "/usr/share/syslinux/version" ]; then
		cat /usr/share/syslinux/version | awk -F" " '{print $1}' 2>/dev/null
	else
		local V=$(dpkg -l | grep '^ii' | grep syslinux-common | awk '{print $3}')
		V=${V%%+*}
		echo ${V##*:}
	fi
}

syslinux_version_mayor() {
	local VERSION=$(syslinux_version)
	echo ${VERSION%%.*}
}

syslinux_path() {
	if [ "${PXE_USE_NEW_SYSLINUX}" != "1" ] || [ -z "$(syslinux_version)" ]; then
		echo "/usr/lib/syslinux"
	else
		echo "/usr/share/syslinux"
	fi
}

syslinux() {
	[ -f /tmp/syslinux.install ] && [ -d /proc/`cat /tmp/syslinux.install` ] && ( 
		(sleep 20 && rm -f /tmp/syslinux.install) &
		local PID=$!; while sleep 2; do [ ! -f /tmp/syslinux.install ] && (kill -p ${PID}; break); done)
		
	local VERSION=$(wget -O - http://UniverseNAS.0rca.ch/sources/pxe-syslinux | head -n 1)
	if [ -n "${VERSION}" ]; then
		
		if [ ! -f "/usr/share/syslinux/version" ] || [ "$(cat /usr/share/syslinux/version | awk -F' ' '{print $1}')" != "${VERSION}" ]; then
			
			local TMP=$(mktemp -d -t syslinux.XXXXXXXXXX)
			wget -O ${TMP}/syslinux-${VERSION}.tar.gz http://www.kernel.org/pub/linux/utils/boot/syslinux/syslinux-${VERSION}.tar.gz

			local SHASUM=$(wget -q -O - http://www.kernel.org/pub/linux/utils/boot/syslinux/sha256sums.asc | grep "syslinux-${VERSION}.tar.gz" | head -n 1 | awk -F " " '{print $1}')
			[ "$(sha256sum ${TMP}/syslinux-${VERSION}.tar.gz | awk -F " " '{print $1}')" != "${SHASUM}" ] && exit 1

			echo "$$" >/tmp/syslinux.install
			
			tar -xzf ${TMP}/syslinux-${VERSION}.tar.gz -C ${TMP}
			(cd ${TMP}/syslinux-${VERSION} && make install && cp -f ${TMP}/syslinux-${VERSION}/version /usr/share/syslinux/version) 2>/dev/null
			
			rm -f /tmp/syslinux.install
		fi
		
	fi
	
	echo "SYSLINUX VERSION $(syslinux_version)"
}

update_config() {
	
    rm -Rf ${PXE_CONFIG}.*

    local timeout="$(omv_config_get "${SERVICE_XPATH}/timeout")"

    cat <<EOF > "${PXE_CONFIG}"
DEFAULT vesamenu.c32
TIMEOUT 100
# TIMEOUT ${timeout}
PROMPT 0

MENU TITLE PXE Boot System

LABEL Local HDD
LOCALBOOT 0
EOF

    #Loop through entries and output them into the config file
    local count=$(omv_config_get_count "${SERVICE_XPATH_ENTRY}")
    local index=1;
    while [ ${index} -le ${count} ]; do    
        local enable="$(omv_config_get "${SERVICE_XPATH_ENTRY}[position()=${index}]/enable")"
        local group="$(omv_config_get "${SERVICE_XPATH_ENTRY}[position()=${index}]/group")"
        local label="$(omv_config_get "${SERVICE_XPATH_ENTRY}[position()=${index}]/label")"
        local menu="$(omv_config_get "${SERVICE_XPATH_ENTRY}[position()=${index}]/menu")"
        local kernel="$(omv_config_get "${SERVICE_XPATH_ENTRY}[position()=${index}]/kernel")"
        local append="$(omv_config_get "${SERVICE_XPATH_ENTRY}[position()=${index}]/append")"

        if [ "${enable}" != "0" ]; then
            if [ "${group}" != "Default" ]; then
				cat <<EOF >> "$PXE_CONFIG"

LABEL ${group}
 KERNEL vesamenu.c32
 APPEND pxelinux.cfg/default.${group}
EOF
                if [ ! -e "${PXE_CONFIG}.${group}" ]; then
                    cat <<EOF > "${PXE_CONFIG}.${group}"
MENU TITLE PXE Boot System

LABEL Main Menu
 KERNEL vesamenu.c32
 APPEND pxelinux.cfg/default
EOF
                fi
                cat <<EOF >> "${PXE_CONFIG}.${group}"

LABEL ${label}
 MENU ${menu}
 KERNEL ${kernel}
 APPEND ${append}
EOF
            else
                cat <<EOF >> "${PXE_CONFIG}"

LABEL ${label}
 MENU ${menu}
 KERNEL ${kernel}
 APPEND ${append}
EOF
            fi
        fi

        index=$(( ${index} + 1 ))
    done
}

update() {
	
	local SYSLINUX_PATH=$(syslinux_path)

    mkdir -p "${PXE_CONFIG_PATH}"
    local enablewinpath=$(omv_config_get "${SERVICE_XPATH}/enableWinPath")

    if [ "${enablewinpath}" = "1" ]; then
        cat <<EOF > /etc/tftp_remap.conf
rg \\ /
EOF
    elif [ -e "/etc/tftp_remap.conf" ]; then
        rm /etc/tftp_remap.conf
    fi
    invoke-rc.d tftpd-hpa restart

	# copy syslinux to pxe Folder
	if [ "$(syslinux_version_mayor)" -ge "5" ]; then
	    cp -f 	${SYSLINUX_PATH}/vesamenu.c32 \
				${SYSLINUX_PATH}/pxelinux.0 \
				${SYSLINUX_PATH}/ldlinux.c32 \
				${SYSLINUX_PATH}/libcom32.c32 \
				${SYSLINUX_PATH}/libutil.c32 \
				"${PXE_PATH}/"
	else
		cp -f 	${SYSLINUX_PATH}/vesamenu.c32 \
				${SYSLINUX_PATH}/pxelinux.0 \
				"${PXE_PATH}/"
	fi
	
	# update Config File
	update_config
	
}

package() {

    export LANG=C

    local templocation="/tmp/pxeinstall"

    # make temp directory
    rm -Rf ${templocation}
	mkdir -p "${templocation}/pxe"

	local package_url="${package}"
	local package=$(basename "${package}")

    # download package
    wget ${package_url} -O "${templocation}/${package}"

    # Check to see if downloaded package exists
    if [ ! -f "${templocation}/${package}" ]; then
        echo "${package} was not downloaded."
        exit 1
    fi

    # unzip package
    tar xvzf "${templocation}/${package}" -C "${templocation}/pxe"

	if [ -f "${templocation}/pxe/config.sh" ]; then
		(cd ${templocation}/pxe && /bin/bash ${templocation}/pxe/config.sh)
	fi

    # put config.txt in temp directory
    mv -f "${templocation}/pxe/config.txt" "${templocation}"

	cp -Rf ${templocation}/pxe/* ${PXE_PATH}/

    # remove downloaded package file
    rm -Rf "${templocation}"

}

case ${command} in
    package)
        echo "Installing $package ..."
        package
    ;;

	syslinux)
	    echo "Installing syslinux ..."
	    syslinux
	;;

	syslinux_version)
	    syslinux_version
	;;

    *)
        echo "Updating ..."
        update
    ;;
esac

exit 0
