#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        SERVICE_XPATH_NAME="pxe"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_delete "${SERVICE_XPATH}"
        fi
		
		if [ -f /var/cache/openmediavault/pxe_packages_cache ]; then
	        rm -f /var/cache/openmediavault/pxe_packages_cache
	    fi
		
		if [ -d /usr/share/syslinux ]; then
	        rm -Rf /usr/share/syslinux
	    fi
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
